[package]
name = "homepage"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.8.0"
askama = { version = "0.12.1", features = ["serde_json", "with-actix-web"] }
askama_actix = "0.14.0"
serde_json = "1.0.118"
